### ISSUE TITLE
找不到注册表   版本  0.19.0

### ISSUE THREAD

**Issue by longletian** [IdeaPloter/PowerToys-Chinese-TransMOD#1]
![image](https://user-images.githubusercontent.com/28197668/90201503-a60c8180-de0d-11ea-8a31-ac2b50430dd6.png)

**Comment by longletian** [comment]
不支持低的版本吗？

**Comment by IdeaPloter** [comment]
请下载对应版本的汉化包使用

**Comment by IdeaPloter** [comment]
噢抱歉，0.19.0 应该没有汉化，因为我制作一半的时候 0.19.1 出了，所以直接去做 0.19.1 了。
推荐你直接安装最新版本 PowerToys，然后使用最新版本的汉化。

**Comment by IdeaPloter** [comment]
还有什么问题欢迎随时来问

**Comment by longletian** [comment]
好了 我的已经在使用了
