### ISSUE TITLE
右键菜单貌似无法汉化吗？

### ISSUE THREAD

**Issue by hyy34** [IdeaPloter/PowerToys-Chinese-TransMOD#2]
要是能自动汉化右键菜单就厉害了。。

**Comment by IdeaPloter** [comment]
右键菜单？你是指哪个呢？

状态栏图标的菜单已经汉化了。
![image](https://user-images.githubusercontent.com/36418285/92989845-ed1f8c80-f509-11ea-84cd-83579c77bcbe.png)

你是希望这个 PowerRename 是中文的吗？
![image](https://user-images.githubusercontent.com/36418285/92989954-9ebebd80-f50a-11ea-931f-e624ceb7ec97.png)

**Comment by hyy34** [comment]
> 右键菜单？你是指哪个呢？
> 
> 状态栏图标的菜单已经汉化了。
> ![image](https://user-images.githubusercontent.com/36418285/92989845-ed1f8c80-f509-11ea-84cd-83579c77bcbe.png)
> 
> 你是希望这个 PowerRename 是中文的吗？
> ![image](https://user-images.githubusercontent.com/36418285/92989954-9ebebd80-f50a-11ea-931f-e624ceb7ec97.png)

是的。就是它！！

**Comment by IdeaPloter** [comment]
> > 右键菜单？你是指哪个呢？
> > 状态栏图标的菜单已经汉化了。
> > ![image](https://user-images.githubusercontent.com/36418285/92989845-ed1f8c80-f509-11ea-84cd-83579c77bcbe.png)
> > 你是希望这个 PowerRename 是中文的吗？
> > ![image](https://user-images.githubusercontent.com/36418285/92989954-9ebebd80-f50a-11ea-931f-e624ceb7ec97.png)
> 
> 是的。就是它！！

汉化这个应该是没问题的，只是我觉得这是这个模块的名称，所以保留了英文。

**Comment by IdeaPloter** [comment]
> > 右键菜单？你是指哪个呢？
> > 状态栏图标的菜单已经汉化了。
> > ![image](https://user-images.githubusercontent.com/36418285/92989845-ed1f8c80-f509-11ea-84cd-83579c77bcbe.png)
> > 你是希望这个 PowerRename 是中文的吗？
> > ![image](https://user-images.githubusercontent.com/36418285/92989954-9ebebd80-f50a-11ea-931f-e624ceb7ec97.png)
> 
> 是的。就是它！！

新的 0.23.0 将会汉化这个右键菜单。
PowerRename --> 批量重命名
解决了这个问题😉
